title: "A framework to compare music generative models with automatic evaluation metrics extended to rhythm."
description: "Songs, code and datasets to replicate the research and the specific results of the paper"
